## NUMPY 

In [2]:
import numpy as np

## Datatypes 

In [3]:
# NumPy's main datatype is ndarray
a1=np.array([1,2,3])
a1

array([1, 2, 3])

In [4]:
type(a1)

numpy.ndarray

In [7]:

a2 =np.array([[1,2,3], [4, 5.0,6]])
a2


array([[1., 2., 3.],
       [4., 5., 6.]])

In [6]:
a3=np.array([[[1,2,3],[4,5,6],[12,34,5.0]],[[1,3,4],[4,7,2], [4,9,6]]])
a3

array([[[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [12., 34.,  5.]],

       [[ 1.,  3.,  4.],
        [ 4.,  7.,  2.],
        [ 4.,  9.,  6.]]])

In [8]:
a1.shape

(3,)

In [9]:
a2.shape

(2, 3)

In [10]:
a3.shape

(2, 3, 3)

In [11]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [12]:
a1

array([1, 2, 3])

In [13]:
a2

array([[1., 2., 3.],
       [4., 5., 6.]])

In [14]:
a3

array([[[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [12., 34.,  5.]],

       [[ 1.,  3.,  4.],
        [ 4.,  7.,  2.],
        [ 4.,  9.,  6.]]])

In [15]:
a1.dtype

dtype('int32')

In [16]:
a3.dtype

dtype('float64')

In [17]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [18]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [21]:
# Create a dataframe from numpy array
import pandas as pd
df=pd.DataFrame(a2)

In [20]:
df

0    1    2
0  1.0  2.0  3.0
1  4.0  5.0  6.0

## NUMPY Array


In [22]:
arr=np.array([1,2,3])
arr

array([1, 2, 3])

In [23]:
arr.dtype

dtype('int32')

In [25]:
ones=np.ones((2,3))

In [26]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [27]:
ones.dtype

dtype('float64')

In [28]:
type(ones)

numpy.ndarray

In [30]:
zeroes=np.zeros((2,3))
zeroes

array([[0., 0., 0.],
       [0., 0., 0.]])

In [31]:
range_arr=np.arange(0,10,2)
range_arr

array([0, 2, 4, 6, 8])

In [33]:
random_array=np.random.randint(0,10,size=(3,5))
random_array

array([[2, 9, 7, 6, 4],
       [8, 2, 2, 9, 8],
       [0, 6, 3, 2, 0]])

In [34]:
random_array.size

15

In [35]:
random_array.shape

(3, 5)

In [37]:
arr2= np.random.random((5,3))
arr2

array([[0.53594428, 0.97014864, 0.1565254 ],
       [0.94733541, 0.04681752, 0.01485229],
       [0.97776011, 0.74702539, 0.04421641],
       [0.66935755, 0.15790616, 0.01953651],
       [0.213434  , 0.91955758, 0.87075017]])

In [41]:
# pseudo number
np.random.seed(seed=0)

arr4= np.random.randint(10, size=(5,3))
arr4


array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

#### Viewing Array and Matrics

In [43]:
np.unique(arr4)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [44]:
a1

array([1, 2, 3])

In [45]:
a2

array([[1., 2., 3.],
       [4., 5., 6.]])

In [46]:
a3

array([[[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [12., 34.,  5.]],

       [[ 1.,  3.,  4.],
        [ 4.,  7.,  2.],
        [ 4.,  9.,  6.]]])

In [47]:
a1[0]

1

In [48]:
a2[0]

array([1., 2., 3.])

In [49]:
a2[1]


array([4., 5., 6.])

#### Manipulating & Comparing Arrays

In [50]:
## arithmetic
a1

array([1, 2, 3])

In [51]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [52]:
ones=np.ones(3)

In [53]:
ones

array([1., 1., 1.])

In [54]:
a1+ones

array([2., 3., 4.])

In [55]:
a1-ones

array([0., 1., 2.])

In [56]:
a1* ones

array([1., 2., 3.])

In [57]:
a2

array([[1., 2., 3.],
       [4., 5., 6.]])

In [58]:
a1* a2

array([[ 1.,  4.,  9.],
       [ 4., 10., 18.]])

In [59]:
a3

array([[[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [12., 34.,  5.]],

       [[ 1.,  3.,  4.],
        [ 4.,  7.,  2.],
        [ 4.,  9.,  6.]]])

ValueError: operands could not be broadcast together with shapes (2,3) (2,3,3) 

In [61]:
a1/ones

array([1., 2., 3.])

In [62]:
a2 // a1

array([[1., 1., 1.],
       [4., 2., 2.]])

In [63]:
 a2 ** 2

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [64]:
np.square(a2)

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [66]:
###  Aggregation 
#performing the same operation on the number of things


In [67]:
a1

array([1, 2, 3])

In [68]:
sum(a1)

6

In [74]:
massive_array= np.random.random(10000)
massive_array

array([0.83881577, 0.6928224 , 0.95799151, ..., 0.67512985, 0.31210011,
       0.57568377])

In [75]:
%timeit sum(massive_array)
%timeit np.sum(massive_array)

1.72 ms ± 92.7 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)
18.4 μs ± 2.96 μs per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [76]:
np.mean(a2)

3.5

In [77]:
np.max(a2)

6.0

In [78]:
np.min(a2)

1.0

In [79]:
np.std(a2)

1.707825127659933

In [80]:
np.var(a2)

2.9166666666666665

In [82]:
np.sqrt(np.var(a2))

1.707825127659933

## Reshaping and transposing

In [83]:
a2.shape

(2, 3)

In [84]:
a3.shape

(2, 3, 3)

In [85]:
a2.reshape(2,3,1)

array([[[1.],
        [2.],
        [3.]],

       [[4.],
        [5.],
        [6.]]])

 # Dot product 

In [86]:
np.random.seed(0)
mat1= np.random.randint(10, size=(5,3))
mat2=np.random.randint(10, size=(5,3))

In [87]:
mat1

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [88]:
mat2

array([[6, 7, 7],
       [8, 1, 5],
       [9, 8, 9],
       [4, 3, 0],
       [3, 5, 0]])

In [89]:
mat1* mat2

array([[30,  0, 21],
       [24,  7, 45],
       [27, 40, 18],
       [16, 21,  0],
       [24, 40,  0]])

In [90]:
# Transpose mat1
mat1.T

array([[5, 3, 3, 4, 8],
       [0, 7, 5, 7, 8],
       [3, 9, 2, 6, 1]])

In [92]:
mat1.T.shape , mat2.T.shape

((3, 5), (3, 5))

In [93]:
mat3= np.dot(mat1, mat2.T)

In [94]:
mat3

array([[ 51,  55,  72,  20,  15],
       [130,  76, 164,  33,  44],
       [ 67,  39,  85,  27,  34],
       [115,  69, 146,  37,  47],
       [111,  77, 145,  56,  64]])

In [95]:
mat3.shape

(5, 5)

 # Comparison Operator

In [96]:
a1>a2

array([[False, False, False],
       [False, False, False]])

In [98]:
a2>a1

array([[False, False, False],
       [ True,  True,  True]])

In [99]:
a1==a2

array([[ True,  True,  True],
       [False, False, False]])

### Sorting array

In [100]:
random_array

array([[2, 9, 7, 6, 4],
       [8, 2, 2, 9, 8],
       [0, 6, 3, 2, 0]])

In [102]:
arr5= np.random.randint(10, size=(4,3))
arr5

array([[2, 3, 8],
       [1, 3, 3],
       [3, 7, 0],
       [1, 9, 9]])

In [103]:
arr5.shape

(4, 3)

In [104]:
np.sort(arr5)

array([[2, 3, 8],
       [1, 3, 3],
       [0, 3, 7],
       [1, 9, 9]])

In [105]:
np.argsort(arr5)

array([[0, 1, 2],
       [0, 1, 2],
       [2, 0, 1],
       [0, 1, 2]], dtype=int64)

In [106]:
np.sort(a1)

array([1, 2, 3])

In [110]:
np.argmax(arr5, axis=1)

array([2, 1, 1, 1], dtype=int64)

 # Turn Images Into Numpy Array

<img src="panda.png" />

In [112]:
from matplotlib.image import imread

panda = imread("panda.png")
print(type(panda))

<class 'numpy.ndarray'>


In [113]:
panda

array([[[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       ...,

       [[0.13333334, 0.07450981, 0.05490196],
        [0.12156863, 0.0627451 , 0.04313726],
        [0.10980392, 0

In [114]:
panda.size, panda.shape

(24465000, (2330, 3500, 3))

In [115]:
panda.ndim

3

In [116]:
panda[:100]

array([[[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       ...,

       [[0.06666667, 0.12156863, 0.07058824],
        [0.06666667, 0.12156863, 0.07058824],
        [0.06666667, 0

In [117]:
panda[:5]

array([[[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.

<img src="car-photo.png"/>

In [118]:
car= imread("car-photo.png")

In [119]:
car

array([[[0.5019608 , 0.50980395, 0.4862745 , 1.        ],
        [0.3372549 , 0.34509805, 0.30588236, 1.        ],
        [0.20392157, 0.21568628, 0.14901961, 1.        ],
        ...,
        [0.64705884, 0.7058824 , 0.54901963, 1.        ],
        [0.59607846, 0.63529414, 0.45882353, 1.        ],
        [0.44705883, 0.47058824, 0.3372549 , 1.        ]],

       [[0.44313726, 0.43529412, 0.40392157, 1.        ],
        [0.3137255 , 0.31764707, 0.27450982, 1.        ],
        [0.2       , 0.21176471, 0.14117648, 1.        ],
        ...,
        [0.5058824 , 0.5372549 , 0.4117647 , 1.        ],
        [0.49803922, 0.52156866, 0.39607844, 1.        ],
        [0.4       , 0.42745098, 0.34117648, 1.        ]],

       [[0.39607844, 0.38039216, 0.34117648, 1.        ],
        [0.31764707, 0.3137255 , 0.27450982, 1.        ],
        [0.28627452, 0.29411766, 0.24705882, 1.        ],
        ...,
        [0.44705883, 0.45882353, 0.32156864, 1.        ],
        [0.45882353, 0.482352

In [120]:
car[:1]

array([[[0.5019608 , 0.50980395, 0.4862745 , 1.        ],
        [0.3372549 , 0.34509805, 0.30588236, 1.        ],
        [0.20392157, 0.21568628, 0.14901961, 1.        ],
        ...,
        [0.64705884, 0.7058824 , 0.54901963, 1.        ],
        [0.59607846, 0.63529414, 0.45882353, 1.        ],
        [0.44705883, 0.47058824, 0.3372549 , 1.        ]]], dtype=float32)