# NumPy Practice

This notebook offers a set of exercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [1]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [13]:
# Create a 1-dimensional NumPy array using np.array()
arr1=np.array([1,2,3,4,5])

# Create a 2-dimensional NumPy array using np.array()
arr2=np.array([[1,2,3],[4,5,6]])


# Create a 3-dimensional Numpy array using np.array()
arr3=np.array([[[1,2,3],[4,5,6],[7,8,9]]])

Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [14]:
# Attributes of 1-dimensional array (shape,
arr1.shape, arr2.shape, arr3.shape
# number of dimensions, data type, size and type)


((5,), (2, 3), (1, 3, 3))

In [16]:
# Attributes of 2-dimensional array
arr2.shape  , arr2.ndim, arr2.dtype, arr2.size, type(arr2)

((2, 3), 2, dtype('int64'), 6, numpy.ndarray)

In [17]:
# Attributes of 3-dimensional array
arr3.shape, arr3.ndim, arr3.dtype, arr3.size, type(arr3)

((1, 3, 3), 3, dtype('int64'), 9, numpy.ndarray)

In [18]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd
df=pd.DataFrame(arr2)
df

0  1  2
0  1  2  3
1  4  5  6

In [20]:
# Create an array of shape (10, 2) with only ones
ones=np.ones((10,2))
ones

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [21]:
# Create an array of shape (7, 2, 3) of only zeros
zeroes=np.zeros((7,2,3))
zeroes

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [22]:
# Create an array within a range of 0 and 100 with step 3
range_array=np.arange(0,100,3)
range_array

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [23]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
arr_ran=np.random.randint(10, size=(7,2))
arr_ran

array([[8, 4],
       [1, 3],
       [8, 1],
       [1, 6],
       [1, 1],
       [1, 8],
       [5, 4]])

In [24]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
arr_4=np.random.random((3,5))
arr_4

array([[0.32060494, 0.34422704, 0.10427063, 0.77366739, 0.82381975],
       [0.62535303, 0.69483627, 0.009153  , 0.89745517, 0.65313138],
       [0.28848105, 0.41537755, 0.48733585, 0.04961566, 0.0282428 ]])

In [27]:
# Set the random seed to 42

np.random.seed(42)
# Create a random array of numbers between 0 & 10 of size (4, 6)
seed_arr=np.random.randint(10, size=(4,6))
seed_arr

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

In [30]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
variable=np.random.randint(10, size=(3,7))
np.unique(variable)


# Find the unique numbers in the array you just created
np.unique(variable)

array([0, 1, 2, 3, 4, 6, 7, 8, 9])

In [31]:
# Find the 0'th index of the latest array you created
variable[0]

array([3, 7, 6, 8, 7, 4, 1])

In [32]:
# Get the first 2 rows of latest array you created
variable[:2]

array([[3, 7, 6, 8, 7, 4, 1],
       [4, 7, 9, 8, 8, 0, 8]])

In [33]:
# Get the first 2 values of the first 2 rows of the latest array
variable[:2,:2]

array([[3, 7],
       [4, 7]])

In [34]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables


arr5=np.random.randint(10, size=(3,5))
arr5

array([[0, 7, 2, 2, 0],
       [4, 9, 6, 9, 8],
       [6, 8, 7, 1, 0]])

In [37]:
# Add the two arrays together
arr5 + ones

ValueError: operands could not be broadcast together with shapes (3,5) (10,2) 

In [38]:
# Create another array of ones of shape (5, 3)
arr6=np.ones((5,3))
arr6

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [40]:
# Try add the array of ones and the other most recent array together
arr6 + arr5

ValueError: operands could not be broadcast together with shapes (5,3) (3,5) 

When you try the last cell, it produces an error. Why do think this is?

How would you fix it?

In [41]:
# Create another array of ones of shape (3, 5)
ones=np.ones((3,5))
ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
# Subtract the new array of ones from the other most recent array


In [42]:
# Multiply the ones array with the latest array
ones * arr5

array([[0., 7., 2., 2., 0.],
       [4., 9., 6., 9., 8.],
       [6., 8., 7., 1., 0.]])

In [43]:
# Take the latest array to the power of 2 using '**'
arr5 ** 2

array([[ 0, 49,  4,  4,  0],
       [16, 81, 36, 81, 64],
       [36, 64, 49,  1,  0]])

In [44]:
# Do the same thing with np.square()
np.square(arr5)

array([[ 0, 49,  4,  4,  0],
       [16, 81, 36, 81, 64],
       [36, 64, 49,  1,  0]])

In [45]:
# Find the mean of the latest array using np.mean()
np.mean(arr5)

4.6

In [46]:
# Find the maximum of the latest array using np.max()
np.max(arr5)

9

In [47]:
# Find the minimum of the latest array using np.min()
np.min(arr5)

0

In [48]:
# Find the standard deviation of the latest array
np.std(arr5)

3.3426536364591137

In [49]:
# Find the variance of the latest array
np.var(arr5)

11.173333333333336

In [ ]:
# Reshape the latest array to (3, 5, 1)


In [50]:
# Transpose the latest array
arr5.T

array([[0, 4, 6],
       [7, 9, 8],
       [2, 6, 7],
       [2, 9, 1],
       [0, 8, 0]])

What does the transpose do?

In [53]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
arr7=np.random.randint(10, size=(3,3))
arr8=np.random.randint(10, size=(3,2))

In [56]:
# Perform a dot product on the two newest arrays you created
np.dot(arr7, arr8)

array([[118,  47],
       [ 51,  21],
       [ 72,  23]])

In [57]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)

arr9=np.random.randint(10, size=(4,3))
arr10=np.random.randint(10,size=(4,3))


In [59]:
# Perform a dot product on the two newest arrays you created
np.dot(arr9.T, arr10)

array([[124, 105, 121],
       [126, 106, 111],
       [ 92, 130, 173]])

It doesn't work. How would you fix it?

In [60]:
# Take the latest two arrays, perform a transpose on one of them and then perform
# a dot product on them both
arr9.T.dot(arr10)

array([[124, 105, 121],
       [126, 106, 111],
       [ 92, 130, 173]])

Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [61]:
# Compare the two arrays with '>'
arr8> arr9

ValueError: operands could not be broadcast together with shapes (3,2) (4,3) 

What happens when you compare the arrays with `>`?

In [64]:
# Compare the two arrays with '>='
arr7 >= arr8

ValueError: operands could not be broadcast together with shapes (3,3) (3,2) 

In [65]:
# Find which elements of the first array are greater than 7
arr8 > 7

array([[False, False],
       [False, False],
       [False, False]])

In [67]:
# Which parts of each array are equal? (try using '==')
arr9 == arr10

array([[False, False, False],
       [False, False, False],
       [False,  True, False],
       [ True, False, False]])

In [68]:
# Sort one of the arrays you just created in ascending order
np.sort(arr5)

array([[0, 0, 2, 2, 7],
       [4, 6, 8, 9, 9],
       [0, 1, 6, 7, 8]])

In [69]:
# Sort the indexes of one of the arrays you just created
np.argsort(arr5)

array([[0, 4, 2, 3, 1],
       [0, 2, 4, 1, 3],
       [4, 3, 0, 2, 1]])